{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "obelus.fullname" . }}
  labels:
    {{- include "obelus.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.apiPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "obelus.fullname" $ }}-api
                port:
                  number: {{ $.Values.api.service.port }}
          {{- end }}
          - path: {{ .Values.ingress.webPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "obelus.fullname" . }}-web
                port:
                  number: {{ .Values.web.service.port }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
